### ISSUE TITLE
submission: deal with install timeouts

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/brain-score#211]
<details>
  <summary>Collecting tensorflow==1.15 [...] socket.timeout: The read operation timed out</summary>
Collecting tensorflow==1.15
  Downloading tensorflow-1.15.0-cp36-cp36m-manylinux2010_x86_64.whl (412.3 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_internal/network/utils.py", line 39, in response_chunks
    decode_content=False,
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Collecting scikit-learn
  Downloading scikit_learn-0.22.2.post1-cp36-cp36m-manylinux1_x86_64.whl (7.1 MB)
Requirement already satisfied: Pillow in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (7.1.2)
Requirement already satisfied: tqdm in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (4.46.0)
Collecting h5py
  Downloading h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9 MB)
Collecting joblib>=0.11
  Downloading joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting scipy>=0.17.0
  Downloading scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (26.1 MB)
Requirement already satisfied: numpy>=1.11.0 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from scikit-learn) (1.18.4)
Requirement already satisfied: six in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from h5py) (1.14.0)
ERROR: model-tools 0.1.0 requires brain-score@ git+https://github.com/brain-score/brain-score, which is not installed.
ERROR: model-tools 0.1.0 requires keras, which is not installed.
ERROR: model-tools 0.1.0 requires tensorflow==1.15, which is not installed.
ERROR: model-tools 0.1.0 requires torch, which is not installed.
ERROR: model-tools 0.1.0 requires torchvision, which is not installed.
ERROR: model-tools 0.1.0 has requirement pandas==0.25.3, but you'll have pandas 1.0.3 which is incompatible.
Installing collected packages: joblib, scipy, scikit-learn, h5py
Successfully installed h5py-2.10.0 joblib-0.14.1 scikit-learn-0.22.2.post1 scipy-1.4.1
Collecting netCDF4==1.5.2
  Downloading netCDF4-1.5.2-cp36-cp36m-manylinux1_x86_64.whl (4.1 MB)
Requirement already satisfied: numpy>=1.7 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from netCDF4==1.5.2) (1.18.4)
Requirement already satisfied: cftime in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from netCDF4==1.5.2) (1.1.2)
Installing collected packages: netCDF4
  Attempting uninstall: netCDF4
    Found existing installation: netCDF4 1.5.3
    Uninstalling netCDF4-1.5.3:
      Successfully uninstalled netCDF4-1.5.3
Successfully installed netCDF4-1.5.2
Collecting awscli
  Downloading awscli-1.18.51-py2.py3-none-any.whl (3.0 MB)
Collecting colorama<0.4.4,>=0.2.5; python_version != "3.4"
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: botocore==1.16.1 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from awscli) (1.16.1)
Collecting PyYAML<5.4,>=3.10; python_version != "3.4"
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Requirement already satisfied: docutils<0.16,>=0.10 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from awscli) (0.15.2)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from awscli) (0.3.3)
Collecting rsa<=3.5.0,>=3.1.2
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from botocore==1.16.1->awscli) (2.8.1)
Requirement already satisfied: urllib3<1.26,>=1.20; python_version != "3.4" in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from botocore==1.16.1->awscli) (1.25.9)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from botocore==1.16.1->awscli) (0.9.5)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: six>=1.5 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.16.1->awscli) (1.14.0)
Building wheels for collected packages: PyYAML
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44621 sha256=287612e825928e89ed436f7c5458fe834913847ad32b99e5f55e919a725fbeae
  Stored in directory: /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/score_models_env_360/.cache/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
Successfully built PyYAML
Installing collected packages: colorama, PyYAML, pyasn1, rsa, awscli
Successfully installed PyYAML-5.3.1 awscli-1.18.51 colorama-0.4.3 pyasn1-0.4.8 rsa-3.4.2
Processing /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/score_models_env_360/brain-score
Requirement already satisfied: numpy>=1.16 in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from brain-score==0.2) (1.18.4)
Requirement already satisfied: brainio_base@ git+https://github.com/brain-score/brainio_base from git+https://github.com/brain-score/brainio_base in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from brain-score==0.2) (0.1.0)
Requirement already satisfied: brainio_collection@ git+https://github.com/brain-score/brainio_collection from git+https://github.com/brain-score/brainio_collection in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from brain-score==0.2) (0.1.0)
Requirement already satisfied: scikit-learn in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from brain-score==0.2) (0.22.2.post1)
Requirement already satisfied: h5py in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from brain-score==0.2) (2.10.0)
Requirement already satisfied: tqdm in /net/storage001.ib.cluster/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages (from brain-score==0.2) (4.46.0)
Collecting gitpython
  Downloading GitPython-3.1.1-py3-none-any.whl (450 kB)
Collecting fire
  Downloading fire-0.3.1.tar.gz (81 kB)
Collecting networkx
  Downloading networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting matplotlib
  Downloading matplotlib-3.2.1-cp36-cp36m-manylinux1_x86_64.whl (12.4 MB)
Collecting tensorflow==1.15
  Downloading tensorflow-1.15.0-cp36-cp36m-manylinux2010_x86_64.whl (412.3 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_360/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
</details>

I'm not sure if these only occor for timeout but we should increase the wait time or attempt restarts.

**Comment by mschrimpf** [comment]
Also happens for pytorch:
<details>
  <summary>Collecting torch [...] socket.timeout: The read operation timed out</summary>
Collecting torch
  Downloading torch-1.5.0-cp36-cp36m-manylinux1_x86_64.whl (752.0 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/om2/group/dicarlo/jenkins/miniconda3/envs/score_models_395/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
</details>

**Comment by mschrimpf** [comment]
reached out to cluster admin if they have seen this error before

**Comment by franzigeiger** [comment]
I have extended the timeout and added a second try(no loop, because if there's an actual problem this would result in an endless loop)

**Comment by mschrimpf** [comment]
ok let's see if 2 is enough, otherwise I think it would be fine to e.g. try 5 times.
